### ISSUE TITLE
conda environment setup issue

### ISSUE THREAD

**Issue by mmaingab** [kmj0792/PolarDSN#5]
Hello,

I found your paper very interesting and would like to thank you for your contribution to this field.
I am trying to run the code from your research, but unfortunately, I am having difficulties setting up the Anaconda virtual environment. Could you kindly share the .yaml file of the conda virtual environment you used for the experiments? My email address is mars9954 @ naver dot com

Thank you very much for your help.

Best regards,

**Comment by kmj0792** [comment]
Thank you for your interest in our work and for reaching out. I’m glad to hear that you found the paper intriguing. 
I understand how challenging setting up a virtual environment can be, especially when replicating experimental setups.

To assist you, I have uploaded the .yaml file containing the specifications of the Conda virtual environment we used for the experiments. You can download it from https://github.com/kmj0792/PolarDSN/blob/main/PolarDSN.yaml.

If you encounter any issues during the setup or have further questions about the code, please feel free to reach out. I'll do my best to assist you.

Thank you again for your interest in our research, and I hope this helps you successfully run the code.

Best regards
